# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/davidstanke/homebrew/Cellar/cmake/3.11.1/bin/cmake

# The command to remove a file.
RM = /Users/davidstanke/homebrew/Cellar/cmake/3.11.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/davidstanke/gitroot/davidstanke/abseil-demo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/davidstanke/gitroot/davidstanke/abseil-demo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/davidstanke/homebrew/Cellar/cmake/3.11.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/davidstanke/homebrew/Cellar/cmake/3.11.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/davidstanke/gitroot/davidstanke/abseil-demo/CMakeFiles /Users/davidstanke/gitroot/davidstanke/abseil-demo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/davidstanke/gitroot/davidstanke/abseil-demo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hello

# Build rule for target.
hello: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello
.PHONY : hello

# fast build rule for target.
hello/fast:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/build
.PHONY : hello/fast

#=============================================================================
# Target rules for targets named absl_malloc_internal

# Build rule for target.
absl_malloc_internal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_malloc_internal
.PHONY : absl_malloc_internal

# fast build rule for target.
absl_malloc_internal/fast:
	$(MAKE) -f abseil-cpp/absl/base/CMakeFiles/absl_malloc_internal.dir/build.make abseil-cpp/absl/base/CMakeFiles/absl_malloc_internal.dir/build
.PHONY : absl_malloc_internal/fast

#=============================================================================
# Target rules for targets named absl_spinlock_wait

# Build rule for target.
absl_spinlock_wait: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_spinlock_wait
.PHONY : absl_spinlock_wait

# fast build rule for target.
absl_spinlock_wait/fast:
	$(MAKE) -f abseil-cpp/absl/base/CMakeFiles/absl_spinlock_wait.dir/build.make abseil-cpp/absl/base/CMakeFiles/absl_spinlock_wait.dir/build
.PHONY : absl_spinlock_wait/fast

#=============================================================================
# Target rules for targets named absl_dynamic_annotations

# Build rule for target.
absl_dynamic_annotations: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_dynamic_annotations
.PHONY : absl_dynamic_annotations

# fast build rule for target.
absl_dynamic_annotations/fast:
	$(MAKE) -f abseil-cpp/absl/base/CMakeFiles/absl_dynamic_annotations.dir/build.make abseil-cpp/absl/base/CMakeFiles/absl_dynamic_annotations.dir/build
.PHONY : absl_dynamic_annotations/fast

#=============================================================================
# Target rules for targets named absl_throw_delegate

# Build rule for target.
absl_throw_delegate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_throw_delegate
.PHONY : absl_throw_delegate

# fast build rule for target.
absl_throw_delegate/fast:
	$(MAKE) -f abseil-cpp/absl/base/CMakeFiles/absl_throw_delegate.dir/build.make abseil-cpp/absl/base/CMakeFiles/absl_throw_delegate.dir/build
.PHONY : absl_throw_delegate/fast

#=============================================================================
# Target rules for targets named absl_base

# Build rule for target.
absl_base: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_base
.PHONY : absl_base

# fast build rule for target.
absl_base/fast:
	$(MAKE) -f abseil-cpp/absl/base/CMakeFiles/absl_base.dir/build.make abseil-cpp/absl/base/CMakeFiles/absl_base.dir/build
.PHONY : absl_base/fast

#=============================================================================
# Target rules for targets named absl_algorithm

# Build rule for target.
absl_algorithm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_algorithm
.PHONY : absl_algorithm

# fast build rule for target.
absl_algorithm/fast:
	$(MAKE) -f abseil-cpp/absl/algorithm/CMakeFiles/absl_algorithm.dir/build.make abseil-cpp/absl/algorithm/CMakeFiles/absl_algorithm.dir/build
.PHONY : absl_algorithm/fast

#=============================================================================
# Target rules for targets named test_instance_tracker_lib

# Build rule for target.
test_instance_tracker_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_instance_tracker_lib
.PHONY : test_instance_tracker_lib

# fast build rule for target.
test_instance_tracker_lib/fast:
	$(MAKE) -f abseil-cpp/absl/container/CMakeFiles/test_instance_tracker_lib.dir/build.make abseil-cpp/absl/container/CMakeFiles/test_instance_tracker_lib.dir/build
.PHONY : test_instance_tracker_lib/fast

#=============================================================================
# Target rules for targets named absl_container

# Build rule for target.
absl_container: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_container
.PHONY : absl_container

# fast build rule for target.
absl_container/fast:
	$(MAKE) -f abseil-cpp/absl/container/CMakeFiles/absl_container.dir/build.make abseil-cpp/absl/container/CMakeFiles/absl_container.dir/build
.PHONY : absl_container/fast

#=============================================================================
# Target rules for targets named absl_debugging

# Build rule for target.
absl_debugging: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_debugging
.PHONY : absl_debugging

# fast build rule for target.
absl_debugging/fast:
	$(MAKE) -f abseil-cpp/absl/debugging/CMakeFiles/absl_debugging.dir/build.make abseil-cpp/absl/debugging/CMakeFiles/absl_debugging.dir/build
.PHONY : absl_debugging/fast

#=============================================================================
# Target rules for targets named absl_leak_check

# Build rule for target.
absl_leak_check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_leak_check
.PHONY : absl_leak_check

# fast build rule for target.
absl_leak_check/fast:
	$(MAKE) -f abseil-cpp/absl/debugging/CMakeFiles/absl_leak_check.dir/build.make abseil-cpp/absl/debugging/CMakeFiles/absl_leak_check.dir/build
.PHONY : absl_leak_check/fast

#=============================================================================
# Target rules for targets named absl_failure_signal_handler

# Build rule for target.
absl_failure_signal_handler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_failure_signal_handler
.PHONY : absl_failure_signal_handler

# fast build rule for target.
absl_failure_signal_handler/fast:
	$(MAKE) -f abseil-cpp/absl/debugging/CMakeFiles/absl_failure_signal_handler.dir/build.make abseil-cpp/absl/debugging/CMakeFiles/absl_failure_signal_handler.dir/build
.PHONY : absl_failure_signal_handler/fast

#=============================================================================
# Target rules for targets named absl_symbolize

# Build rule for target.
absl_symbolize: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_symbolize
.PHONY : absl_symbolize

# fast build rule for target.
absl_symbolize/fast:
	$(MAKE) -f abseil-cpp/absl/debugging/CMakeFiles/absl_symbolize.dir/build.make abseil-cpp/absl/debugging/CMakeFiles/absl_symbolize.dir/build
.PHONY : absl_symbolize/fast

#=============================================================================
# Target rules for targets named absl_stack_consumption

# Build rule for target.
absl_stack_consumption: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_stack_consumption
.PHONY : absl_stack_consumption

# fast build rule for target.
absl_stack_consumption/fast:
	$(MAKE) -f abseil-cpp/absl/debugging/CMakeFiles/absl_stack_consumption.dir/build.make abseil-cpp/absl/debugging/CMakeFiles/absl_stack_consumption.dir/build
.PHONY : absl_stack_consumption/fast

#=============================================================================
# Target rules for targets named absl_examine_stack

# Build rule for target.
absl_examine_stack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_examine_stack
.PHONY : absl_examine_stack

# fast build rule for target.
absl_examine_stack/fast:
	$(MAKE) -f abseil-cpp/absl/debugging/CMakeFiles/absl_examine_stack.dir/build.make abseil-cpp/absl/debugging/CMakeFiles/absl_examine_stack.dir/build
.PHONY : absl_examine_stack/fast

#=============================================================================
# Target rules for targets named absl_stacktrace

# Build rule for target.
absl_stacktrace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_stacktrace
.PHONY : absl_stacktrace

# fast build rule for target.
absl_stacktrace/fast:
	$(MAKE) -f abseil-cpp/absl/debugging/CMakeFiles/absl_stacktrace.dir/build.make abseil-cpp/absl/debugging/CMakeFiles/absl_stacktrace.dir/build
.PHONY : absl_stacktrace/fast

#=============================================================================
# Target rules for targets named absl_memory

# Build rule for target.
absl_memory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_memory
.PHONY : absl_memory

# fast build rule for target.
absl_memory/fast:
	$(MAKE) -f abseil-cpp/absl/memory/CMakeFiles/absl_memory.dir/build.make abseil-cpp/absl/memory/CMakeFiles/absl_memory.dir/build
.PHONY : absl_memory/fast

#=============================================================================
# Target rules for targets named absl_meta

# Build rule for target.
absl_meta: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_meta
.PHONY : absl_meta

# fast build rule for target.
absl_meta/fast:
	$(MAKE) -f abseil-cpp/absl/meta/CMakeFiles/absl_meta.dir/build.make abseil-cpp/absl/meta/CMakeFiles/absl_meta.dir/build
.PHONY : absl_meta/fast

#=============================================================================
# Target rules for targets named absl_numeric

# Build rule for target.
absl_numeric: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_numeric
.PHONY : absl_numeric

# fast build rule for target.
absl_numeric/fast:
	$(MAKE) -f abseil-cpp/absl/numeric/CMakeFiles/absl_numeric.dir/build.make abseil-cpp/absl/numeric/CMakeFiles/absl_numeric.dir/build
.PHONY : absl_numeric/fast

#=============================================================================
# Target rules for targets named absl_int128

# Build rule for target.
absl_int128: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_int128
.PHONY : absl_int128

# fast build rule for target.
absl_int128/fast:
	$(MAKE) -f abseil-cpp/absl/numeric/CMakeFiles/absl_int128.dir/build.make abseil-cpp/absl/numeric/CMakeFiles/absl_int128.dir/build
.PHONY : absl_int128/fast

#=============================================================================
# Target rules for targets named absl_strings

# Build rule for target.
absl_strings: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_strings
.PHONY : absl_strings

# fast build rule for target.
absl_strings/fast:
	$(MAKE) -f abseil-cpp/absl/strings/CMakeFiles/absl_strings.dir/build.make abseil-cpp/absl/strings/CMakeFiles/absl_strings.dir/build
.PHONY : absl_strings/fast

#=============================================================================
# Target rules for targets named absl_synchronization

# Build rule for target.
absl_synchronization: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_synchronization
.PHONY : absl_synchronization

# fast build rule for target.
absl_synchronization/fast:
	$(MAKE) -f abseil-cpp/absl/synchronization/CMakeFiles/absl_synchronization.dir/build.make abseil-cpp/absl/synchronization/CMakeFiles/absl_synchronization.dir/build
.PHONY : absl_synchronization/fast

#=============================================================================
# Target rules for targets named absl_time

# Build rule for target.
absl_time: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_time
.PHONY : absl_time

# fast build rule for target.
absl_time/fast:
	$(MAKE) -f abseil-cpp/absl/time/CMakeFiles/absl_time.dir/build.make abseil-cpp/absl/time/CMakeFiles/absl_time.dir/build
.PHONY : absl_time/fast

#=============================================================================
# Target rules for targets named absl_bad_optional_access

# Build rule for target.
absl_bad_optional_access: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_bad_optional_access
.PHONY : absl_bad_optional_access

# fast build rule for target.
absl_bad_optional_access/fast:
	$(MAKE) -f abseil-cpp/absl/types/CMakeFiles/absl_bad_optional_access.dir/build.make abseil-cpp/absl/types/CMakeFiles/absl_bad_optional_access.dir/build
.PHONY : absl_bad_optional_access/fast

#=============================================================================
# Target rules for targets named absl_span

# Build rule for target.
absl_span: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_span
.PHONY : absl_span

# fast build rule for target.
absl_span/fast:
	$(MAKE) -f abseil-cpp/absl/types/CMakeFiles/absl_span.dir/build.make abseil-cpp/absl/types/CMakeFiles/absl_span.dir/build
.PHONY : absl_span/fast

#=============================================================================
# Target rules for targets named absl_optional

# Build rule for target.
absl_optional: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_optional
.PHONY : absl_optional

# fast build rule for target.
absl_optional/fast:
	$(MAKE) -f abseil-cpp/absl/types/CMakeFiles/absl_optional.dir/build.make abseil-cpp/absl/types/CMakeFiles/absl_optional.dir/build
.PHONY : absl_optional/fast

#=============================================================================
# Target rules for targets named absl_bad_any_cast

# Build rule for target.
absl_bad_any_cast: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_bad_any_cast
.PHONY : absl_bad_any_cast

# fast build rule for target.
absl_bad_any_cast/fast:
	$(MAKE) -f abseil-cpp/absl/types/CMakeFiles/absl_bad_any_cast.dir/build.make abseil-cpp/absl/types/CMakeFiles/absl_bad_any_cast.dir/build
.PHONY : absl_bad_any_cast/fast

#=============================================================================
# Target rules for targets named absl_variant

# Build rule for target.
absl_variant: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_variant
.PHONY : absl_variant

# fast build rule for target.
absl_variant/fast:
	$(MAKE) -f abseil-cpp/absl/types/CMakeFiles/absl_variant.dir/build.make abseil-cpp/absl/types/CMakeFiles/absl_variant.dir/build
.PHONY : absl_variant/fast

#=============================================================================
# Target rules for targets named absl_any

# Build rule for target.
absl_any: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_any
.PHONY : absl_any

# fast build rule for target.
absl_any/fast:
	$(MAKE) -f abseil-cpp/absl/types/CMakeFiles/absl_any.dir/build.make abseil-cpp/absl/types/CMakeFiles/absl_any.dir/build
.PHONY : absl_any/fast

#=============================================================================
# Target rules for targets named absl_utility

# Build rule for target.
absl_utility: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_utility
.PHONY : absl_utility

# fast build rule for target.
absl_utility/fast:
	$(MAKE) -f abseil-cpp/absl/utility/CMakeFiles/absl_utility.dir/build.make abseil-cpp/absl/utility/CMakeFiles/absl_utility.dir/build
.PHONY : absl_utility/fast

hello.o: hello.cpp.o

.PHONY : hello.o

# target to build an object file
hello.cpp.o:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/hello.cpp.o
.PHONY : hello.cpp.o

hello.i: hello.cpp.i

.PHONY : hello.i

# target to preprocess a source file
hello.cpp.i:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/hello.cpp.i
.PHONY : hello.cpp.i

hello.s: hello.cpp.s

.PHONY : hello.s

# target to generate assembly for a file
hello.cpp.s:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/hello.cpp.s
.PHONY : hello.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... hello"
	@echo "... absl_malloc_internal"
	@echo "... absl_spinlock_wait"
	@echo "... absl_dynamic_annotations"
	@echo "... absl_throw_delegate"
	@echo "... absl_base"
	@echo "... absl_algorithm"
	@echo "... test_instance_tracker_lib"
	@echo "... absl_container"
	@echo "... absl_debugging"
	@echo "... absl_leak_check"
	@echo "... absl_failure_signal_handler"
	@echo "... absl_symbolize"
	@echo "... absl_stack_consumption"
	@echo "... absl_examine_stack"
	@echo "... absl_stacktrace"
	@echo "... absl_memory"
	@echo "... absl_meta"
	@echo "... absl_numeric"
	@echo "... absl_int128"
	@echo "... absl_strings"
	@echo "... absl_synchronization"
	@echo "... absl_time"
	@echo "... absl_bad_optional_access"
	@echo "... absl_span"
	@echo "... absl_optional"
	@echo "... absl_bad_any_cast"
	@echo "... absl_variant"
	@echo "... absl_any"
	@echo "... absl_utility"
	@echo "... hello.o"
	@echo "... hello.i"
	@echo "... hello.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

